apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quant-ux-backend-claim0
  namespace: quant-ux
  labels:
    app: quant-ux-backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
