kind: ConfigMap
apiVersion: v1
metadata:
  name: quant-ux-fe-configmap
  namespace: quant-ux
data:
  QUX_AUTH: qux
  QUX_KEYCLOAK_CLIENT: ""
  QUX_KEYCLOAK_REALM: ""
  QUX_KEYCLOAK_URL: ""
  QUX_PROXY_URL: http://quant-ux-backend:8080
  QUX_WS_URL: ws://quant-ux.local/ws