apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
    app.kubernetes.io/component: mongo
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/name: mongo
spec:
  ports:
    - name: "27017-tcp"
      protocol: TCP
      port: 27017
      targetPort: 27017
  internalTrafficPolicy: Cluster
  selector:
    app: mongo
    deploymentconfig: mongo
status:
  loadBalancer: {}