apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim0
  labels:
    app: mongo
    app.kubernetes.io/component: mongo
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/name: mongo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
status: {}
