apiVersion: v1
kind: Service
metadata:
  name: quant-ux-websocket
  labels:
    app: quant-ux-websocket
spec:
  ports:
    - name: "8086-tcp"
      protocol: TCP
      port: 8086
      targetPort: 8086
  selector:
    app: quant-ux-websocket
