apiVersion: v1
kind: Service
metadata:
  name: quant-ux-frontend
  labels:
    app: quant-ux-frontend
spec:
  type: NodePort
  selector:
    app: quant-ux-frontend
  ports:
    - name: "8082-tcp"
      protocol: TCP
      port: 8082
      targetPort: 8082
